### ISSUE TITLE
Support for Quests

### ISSUE THREAD

**Issue by EscolarProgramming** [ZombieStriker/QualityArmory#12]
Hello,
actually on 1.12.2 we are using CrackShot and (via the api) we've created a bridge to Quests (https://www.spigotmc.org/resources/quests.3711/). For 1.13 we want to move to QualityArmory, because it has a lot of advantages. But unfortunately as well the plugin itself as the api don't support a connection to Quests.
So could you please add a bridge to Quests?
Or at least add a method to your api which gets fired if a player shoots with a weapon so we can build our own bridge. Actually we use an own coded bridge using the WeaponPrepareShootEvent of CrackShot (https://github.com/Shampaggon/CrackShot/wiki/Hooking-into-CrackShot#weaponprepareshootevent). 

Thank you in advance,
Escolar

**Comment by ZombieStriker** [comment]
With new new update (V1.1.120), there are now two new events: QAWeaponPrepareShootEvent and QAWeaponDamageEntityEvent. The first event is fired whenever any gun is about to shoot, and the second event is called once a bullet hits an entity. Since they are relatively similar to what crackshot has, the conversion should be simple.
