### ISSUE TITLE
Automatic weapons do not stop firing when left click is released

### ISSUE THREAD

**Issue by IgnorantMountaineer** [ZombieStriker/QualityArmory#129]
When automatic is the default fire mode, shift is the alt mode, left click is fire, and right click is zoom: the gun will not stop firing when the left click button is released as we would come to expect.

Thanks so much ZombieStriker :)

**Comment by ZombieStriker** [comment]
This is an issue with the way minecraft/spigot is coded. Minecraft does not send any information to the server when the left mouse buttton is released, only when it is pressed. Because of this, that is why I had to check if the player is sneaking and use that as the toggle instead of the left mouse button.

Hopefully one day they will add a feature that requires listening for when the mouse button is released, but until then, this is the best we have.

**Comment by IgnorantMountaineer** [comment]
That's fair. Thanks for checking it. The one idea I have was placing an invisible block in front of the player. The event is called when the player is mining. Might be difficult to implement though
