### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by thonking3** [ZombieStriker/QualityArmory#13]
the guns no damage the players in the server or mobs please help me , version 1.1.121

**Comment by thonking3** [comment]
I will try it at lower version

**Comment by thonking3** [comment]
And the console :WARN: Skipping entity Monkey :D??

**Comment by ZombieStriker** [comment]
Before trying an older version, just create a test server with no other plugins installed. If you do that, are you able to damage entities?

If so, then the issue is that one of the plugin is conflicting with QA. Re-add the plugin individually and check each one until you find the one that is stopping the mob from being damaged. Once you do, either post it here and I'll make a patch for it, or remove it if it unneeded and close this issue.

**Comment by thonking3** [comment]
Ok thank you
