### ISSUE TITLE
Support for Dead Society

### ISSUE THREAD

**Issue by keough99** [ZombieStriker/QualityArmory#18]
could support for the [Dead Society](https://www.spigotmc.org/resources/%E2%98%A2-deadsociety-%E2%98%A3-zombie-apocalypse-%E2%98%A3.48823/) plugin be added?

**Comment by ZombieStriker** [comment]
Unless that plugin supports items with custom data (like the unbreakable tag, custom display names, and durability), I don't think there is anything on my end that I can do to add support. What I would suggest is to ask the developer of that plugin to add custom item support directly into that plugin by having them serialize the ItemStacks for the shops or chests so that all the data is copied.
