### ISSUE TITLE
[Feature]: Bedrock Resource Pack

### ISSUE THREAD

**Issue by BobtheBob123456** [ZombieStriker/QualityArmory#360]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

New mechanic

### Description

Hello,
So basically, we play on a geyser server, and as such, the bedrock players cannot see textures. Can we please have a bedrock version of the resource pack?

Thanks.

**Comment by WongIong** [comment]
So geysermc is now working at CustomModelData, https://github.com/GeyserMC/Geyser/issues/210
Before they finish the works, we could never show a custom texture on bedrock because their coding is different from JAVA.
And also, after they finish, we have to do the texturepack convertion ourself because ya Bedrock's coding is different from JAVA.

**Comment by Lorenzo0111** [comment]
Hey, thanks for opening an issue.
Sorry for the delays in my replies.

This is hard for me since i don't know how to create a bedrock resourcepack. Also as @WongIong mentioned above, we need to wait for Geyser to do this.

**Comment by BobtheBob123456** [comment]
Geyser already implemented custom model data into the main version of
geyser. They did it a couple of days ago, except they haven't implemented
blocks yet.

**Comment by Lorenzo0111** [comment]
Read here: https://learn.microsoft.com/en-us/minecraft/creator/documents/convertingtexturepacks
